DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS shows;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS show_seats;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS booking_seats;
